name = "Material Lite"
license = "Apache License 2.0"
licenselink = "https://github.com/joostvanderlaan/hugo-material-design-lite-performance/blob/master/LICENSE.md"
description = "A hugo theme optimized for performance & HTTP/2 based on Google's Material Design Lite"
homepage = "https://github.com/joostvanderlaan/hugo-material-design-lite-performance/"
tags = ["performance", "material", "design", "lite", "google"]
min_version = 0.15

[author]
  name = "Joost van der Laan"
  homepage = "https://joostvanderlaan.nl"

# If porting an existing theme
[original]
  name = "Material Design Lite"
  homepage = "http://www.getmdl.io"
  repo = "https://github.com/google/material-design-lite"
